[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
via_ir = true
bytecode_hash = "none"
cbor_metadata = false

fs_permissions = [
    { access = "read", path = "script" },
    { access = "write", path = "script" },
]


ignore = [
    "lib/**",
    "lib/BaseFactory",
    "lib/euler-vault-kit",
    "src/EVault/EVault.sol",
    "src/EVault/shared/types/VaultStorage.sol",
    "src/EVault/shared/types/VaultCache.sol",
    "test/mocks/TestERC20.sol",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
